"use client";
import { useMemo, useState } from "react";

type Job={id:string;title:string;company:string;location:string;workplace:"Remote"|"Hybrid"|"On-site"|"Unknown";pay:string;source:string;url:string;posted:string;matched:string[];note?:string};
const samples:Job[]=[
 {id:"s1",title:"Senior Business Analyst",company:"Northstar Health",location:"Phoenix, AZ",workplace:"Hybrid",pay:"$98,000â€“$126,000",source:"Greenhouse",url:"https://boards.greenhouse.io/",posted:"Sample result",matched:["business analyst","SQL"],note:"Strong healthcare match"},
 {id:"s2",title:"Data & Reporting Analyst",company:"Fable",location:"United States",workplace:"Remote",pay:"$82,000â€“$110,000",source:"Ashby",url:"https://jobs.ashbyhq.com/",posted:"Sample result",matched:["data analyst","Tableau"]},
 {id:"s3",title:"Operations Analyst II",company:"Juniper Labs",location:"Denver, CO",workplace:"On-site",pay:"Not listed",source:"Lever",url:"https://jobs.lever.co/",posted:"Sample result",matched:["operations analyst"]}
];
const csv=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;
const stateAliases:Record<string,string>={alabama:"al",alaska:"ak",arizona:"az",arkansas:"ar",california:"ca",colorado:"co",connecticut:"ct",delaware:"de",florida:"fl",georgia:"ga",hawaii:"hi",idaho:"id",illinois:"il",indiana:"in",iowa:"ia",kansas:"ks",kentucky:"ky",louisiana:"la",maine:"me",maryland:"md",massachusetts:"ma",michigan:"mi",minnesota:"mn",mississippi:"ms",missouri:"mo",montana:"mt",nebraska:"ne",nevada:"nv","new hampshire":"nh","new jersey":"nj","new mexico":"nm","new york":"ny","north carolina":"nc","north dakota":"nd",ohio:"oh",oklahoma:"ok",oregon:"or",pennsylvania:"pa","rhode island":"ri","south carolina":"sc","south dakota":"sd",tennessee:"tn",texas:"tx",utah:"ut",vermont:"vt",virginia:"va",washington:"wa","west virginia":"wv",wisconsin:"wi",wyoming:"wy","district of columbia":"dc"};
const stateNames:Record<string,string>=Object.fromEntries(Object.entries(stateAliases).map(([name,abbreviation])=>[abbreviation,name]));
const parseTerms=(value:string)=>value.split(/[,\n]/).map(term=>term.trim().toLowerCase()).filter(Boolean);
const containsTerm=(value:string,term:string)=>{const text=String(value||"").toLowerCase();if(term.length>2)return text.includes(term);const words=` ${text.replace(/[^a-z0-9+#.]+/g," ")} `;return words.includes(` ${term} `)};
const locationMatches=(job:Job,locationTerms:string[])=>{if(!locationTerms.length)return true;const location=String(job.location||"").toLowerCase(),words=` ${location.replace(/[^a-z0-9]+/g," ")} `;return locationTerms.some(term=>{if(term==="remote")return job.workplace==="Remote"||location.includes("remote");const aliases=[term,stateAliases[term],stateNames[term]].filter(Boolean);return aliases.some(alias=>alias.length<=2?words.includes(` ${alias} `):location.includes(alias))})};

const publicJobUrl=(job:Job)=>{const url=String(job.url||"");if(job.source!=="SmartRecruiters")return url;const match=url.match(/api\.smartrecruiters\.com\/(?:api-)?v1\/companies\/([^/]+)\/postings\/([^/?#]+)/i);if(!match)return url;const slug=job.title.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");return `https://jobs.smartrecruiters.com/${match[1]}/${match[2]}-${slug}`};
export default function Home(){
 const [titles,setTitles]=useState("business analyst, data analyst, operations analyst"); const [keywords,setKeywords]=useState("SQL, Tableau, process improvement"); const [locations,setLocations]=useState(""); const [exclude,setExclude]=useState("senior director, commission only"); const [remoteOnly,setRemoteOnly]=useState(false); const [jobs,setJobs]=useState<Job[]>(samples); const [state,setState]=useState<"ready"|"scanning"|"done"|"error">("ready"); const [message,setMessage]=useState("Sample results are shown. Run a search to check the refreshed public index."); const [selected,setSelected]=useState<string[]>([]); const [query,setQuery]=useState("");
 const shown=useMemo(()=>{const q=query.toLowerCase();return jobs.filter(j=>!q||`${j.title} ${j.company} ${j.location} ${j.source} ${j.matched.join(" ")}`.toLowerCase().includes(q))},[jobs,query]);
 async function scan(){if(!titles.trim()&&!keywords.trim()){setState("error");setMessage("Enter at least one job title or keyword.");return}setState("scanning");setMessage("Searching the refreshed public job index...");setSelected([]);try{const response=await fetch("/data/jobs.json",{cache:"no-store"});if(!response.ok)throw new Error("The job index is temporarily unavailable.");const data=await response.json();const titleTerms=parseTerms(titles),keywordTerms=parseTerms(keywords),locationTerms=parseTerms(locations),excludeTerms=parseTerms(exclude);const matches=(data.jobs||[]).map((job:Job&{description?:string})=>{const titleMatches=titleTerms.filter(term=>containsTerm(job.title,term)),keywordMatches=keywordTerms.filter(term=>containsTerm(`${job.title} ${job.description||""} ${job.location} ${job.url}`,term));return{...job,matched:[...new Set([...titleMatches,...keywordMatches])],keywordMatchCount:keywordMatches.length}}).filter((job:Job&{description?:string;keywordMatchCount:number})=>{const hay=`${job.title} ${job.description||""} ${job.location}`;const titleMatch=!titleTerms.length||titleTerms.some(term=>containsTerm(job.title,term));const keywordOnlyMatch=titleTerms.length||!keywordTerms.length||job.keywordMatchCount>0;return titleMatch&&keywordOnlyMatch&&locationMatches(job,locationTerms)&&!excludeTerms.some(term=>containsTerm(hay,term))&&(!remoteOnly||job.workplace==="Remote")}).sort((a:{keywordMatchCount:number;matched:string[]},b:{keywordMatchCount:number;matched:string[]})=>b.keywordMatchCount-a.keywordMatchCount||b.matched.length-a.matched.length);setJobs(matches);setState("done");const updated=data.updatedAt?new Date(data.updatedAt).toLocaleString():"not refreshed yet";setMessage(`Found ${matches.length} matching jobs across ${data.sourceCount||0} public ATS boards. Keywords rank results but do not exclude title and location matches. Index updated ${updated}.`)}catch(e){setState("error");setMessage(e instanceof Error?e.message:"The search could not be completed.")}} function exportCsv(){const list=selected.length?jobs.filter(j=>selected.includes(j.id)):shown;const rows=[["Title","Company","Location","Workplace","Pay range","Source","Posted","Matched keywords","Notes","URL"],...list.map(j=>[j.title,j.company,j.location,j.workplace,j.pay,j.source,j.posted,j.matched.join("; "),j.note||"",publicJobUrl(j)])];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(csv).join(",")).join("\r\n")],{type:"text/csv"}));a.download=`job-compass-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <main>
  <header className="topbar"><a className="brand" href="#top"><b>JC</b><span>JOB COMPASS</span></a><nav><a href="#search">Search</a><a href="#results">Results</a><a href="#how">How it works</a></nav><div className="live"><i/>Public pages only</div></header>
  <section className="hero" id="top"><div className="eyebrow">YOUR PERSONAL JOB DISCOVERY WORKBENCH</div><h1>Find the roles worth<br/><em>your time.</em></h1><p>Search across public company career pages and ATS boards. Job Compass discovers likely listings, verifies their metadata and descriptions, and turns the matches into one clean shortlist.</p><div className="coverage"><span>GREENHOUSE</span><span>ASHBY</span><span>LEVER</span><span>SMARTRECRUITERS</span><span>ICIMS*</span><span>CAREER PAGES</span></div></section>
  <section className="workspace search-only" id="search">
   <div className="panel filters filters-wide"><Heading n="01" title="Search the job market" copy="Enter what you want. Job Compass discovers and verifies public job listings for you."/><div className="grid"><label>Job titles<input value={titles} onChange={e=>setTitles(e.target.value)} placeholder="Business analyst, data analyst"/></label><label>Keywords (optional; matches ranked higher)<input value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="SQL, Tableau, process improvement"/></label><label>Locations (comma-separated)<input value={locations} onChange={e=>setLocations(e.target.value)} placeholder="Phoenix, Denver, Remote"/></label><label>Exclude<input value={exclude} onChange={e=>setExclude(e.target.value)} placeholder="Senior director, commission only"/></label></div><div className="remote-row"><button className={remoteOnly?"switch on":"switch"} onClick={()=>setRemoteOnly(!remoteOnly)} aria-pressed={remoteOnly}><span/></button><div><strong>Remote roles only</strong><small>Include jobs explicitly marked remote</small></div></div><button className="scan" onClick={scan} disabled={state==="scanning"}>{state==="scanning"?"Searching...":"Search jobs"}<span>→</span></button><p className={`status ${state}`} aria-live="polite">{message}</p><div className="notice discovery"><b>↗</b><p><strong>Verified public listings.</strong> Results come from a free index refreshed throughout the day from public ATS feeds, career-page metadata, and job-description HTML. Login-only pages are not bypassed.</p></div></div>
  </section>  <section className="results" id="results"><div className="results-head"><div><div className="eyebrow">YOUR SHORTLIST</div><h2>{shown.length} opportunities</h2><p>Review, annotate, select, and export. Notes stay in this browser session.</p></div><button className="export" onClick={exportCsv} disabled={!shown.length}>â†“ Export {selected.length?`${selected.length} selected`:"all"} as CSV</button></div><div className="tools"><input aria-label="Filter results" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter by title, company, or locationâ€¦"/><button onClick={()=>setSelected(selected.length===shown.length?[]:shown.map(j=>j.id))}>{selected.length===shown.length&&shown.length?"Clear selection":"Select all"}</button></div><div className="job-list">
   {shown.map(job=><article className="job" key={job.id}><label className="check"><input type="checkbox" checked={selected.includes(job.id)} onChange={()=>setSelected(v=>v.includes(job.id)?v.filter(x=>x!==job.id):[...v,job.id])}/><span/></label><div className="job-body"><div className="job-top"><div><div className="company">{job.company} Â· {job.source}</div><h3><a href={publicJobUrl(job)} target="_blank" rel="noreferrer">{job.title} <small>â†—</small></a></h3></div><span className={`workplace ${job.workplace.toLowerCase().replace("-","")}`}>{job.workplace}</span></div><div className="facts"><span>âŒ– {job.location}</span><span>â—« {job.pay}</span><span>â—· {job.posted}</span></div><div className="matches">{job.matched.map(m=><span key={m}>{m}</span>)}</div><input className="note" value={job.note||""} onChange={e=>setJobs(v=>v.map(j=>j.id===job.id?{...j,note:e.target.value}:j))} placeholder="Add a private noteâ€¦"/></div></article>)}
   {!shown.length&&<div className="empty"><b>âŒ</b><h3>No matches yet</h3><p>Try broader titles or remove a location filter.</p></div>}
  </div></section>
  <section className="how" id="how"><div><div className="eyebrow">BUILT FOR A FOCUSED SEARCH</div><h2>From noisy pages to a useful list.</h2></div><ol><li><b>1</b><strong>Describe the role</strong><p>Enter titles, skills, locations, and exclusions.</p></li><li><b>2</b><strong>Discover and verify</strong><p>Public job pages are found, fetched, and checked.</p></li><li><b>3</b><strong>Make it yours</strong><p>Add notes and export a tidy CSV for follow-up.</p></li></ol></section>
  <footer><strong>JOB COMPASS</strong><p>Public job discovery, organized.</p><small>*Dynamic or protected pages may return limited results.</small></footer>
 </main>
}
function Heading({n,title,copy}:{n:string;title:string;copy:string}){return <div className="heading"><span>{n}</span><div><h2>{title}</h2><p>{copy}</p></div></div>}
