"use client";
import { useMemo, useState } from "react";

type Job={id:string;title:string;company:string;location:string;workplace:"Remote"|"Hybrid"|"On-site"|"Unknown";pay:string;source:string;url:string;posted:string;matched:string[];note?:string};
const samples:Job[]=[
 {id:"s1",title:"Senior Business Analyst",company:"Northstar Health",location:"Phoenix, AZ",workplace:"Hybrid",pay:"$98,000–$126,000",source:"Greenhouse",url:"https://boards.greenhouse.io/",posted:"Sample result",matched:["business analyst","SQL"],note:"Strong healthcare match"},
 {id:"s2",title:"Data & Reporting Analyst",company:"Fable",location:"United States",workplace:"Remote",pay:"$82,000–$110,000",source:"Ashby",url:"https://jobs.ashbyhq.com/",posted:"Sample result",matched:["data analyst","Tableau"]},
 {id:"s3",title:"Operations Analyst II",company:"Juniper Labs",location:"Denver, CO",workplace:"On-site",pay:"Not listed",source:"Lever",url:"https://jobs.lever.co/",posted:"Sample result",matched:["operations analyst"]}
];
const csv=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;

export default function Home(){
 const [sources,setSources]=useState(""); const [titles,setTitles]=useState("business analyst, data analyst, operations analyst"); const [keywords,setKeywords]=useState("SQL, Tableau, process improvement"); const [locations,setLocations]=useState(""); const [exclude,setExclude]=useState("senior director, commission only"); const [remoteOnly,setRemoteOnly]=useState(false); const [jobs,setJobs]=useState<Job[]>(samples); const [state,setState]=useState<"ready"|"scanning"|"done"|"error">("ready"); const [message,setMessage]=useState("Sample results are shown. Add sources to run a live scan."); const [selected,setSelected]=useState<string[]>([]); const [query,setQuery]=useState("");
 const shown=useMemo(()=>{const q=query.toLowerCase();return jobs.filter(j=>!q||`${j.title} ${j.company} ${j.location} ${j.source} ${j.matched.join(" ")}`.toLowerCase().includes(q))},[jobs,query]);
 async function scan(){if(!sources.trim()){setState("error");setMessage("Add at least one public career page or ATS URL.");return}setState("scanning");setMessage("Reading public job pages and organizing the details…");setSelected([]);try{const r=await fetch("/api/scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sources,titles,keywords,locations,exclude,remoteOnly})});const data=await r.json();if(!r.ok)throw new Error(data.error||"The scan could not be completed.");setJobs(data.jobs);setState("done");setMessage(data.message)}catch(e){setState("error");setMessage(e instanceof Error?e.message:"The scan could not be completed.")}}
 function exportCsv(){const list=selected.length?jobs.filter(j=>selected.includes(j.id)):shown;const rows=[["Title","Company","Location","Workplace","Pay range","Source","Posted","Matched keywords","Notes","URL"],...list.map(j=>[j.title,j.company,j.location,j.workplace,j.pay,j.source,j.posted,j.matched.join("; "),j.note||"",j.url])];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(csv).join(",")).join("\r\n")],{type:"text/csv"}));a.download=`job-compass-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <main>
  <header className="topbar"><a className="brand" href="#top"><b>JC</b><span>JOB COMPASS</span></a><nav><a href="#search">Search</a><a href="#results">Results</a><a href="#how">How it works</a></nav><div className="live"><i/>Public pages only</div></header>
  <section className="hero" id="top"><div className="eyebrow">YOUR PERSONAL JOB DISCOVERY WORKBENCH</div><h1>Find the roles worth<br/><em>your time.</em></h1><p>An Indeed-style search for the sources you trust. Scan company career pages and public ATS boards, match the language that matters, and turn scattered listings into one clean shortlist.</p><div className="coverage"><span>GREENHOUSE</span><span>ASHBY</span><span>LEVER</span><span>SMARTRECRUITERS</span><span>ICIMS*</span><span>CAREER PAGES</span></div></section>
  <section className="workspace" id="search">
   <div className="panel sources"><Heading n="01" title="Add your sources" copy="One public career page or job-board URL per line."/><label>Career page URLs<textarea value={sources} onChange={e=>setSources(e.target.value)} placeholder={"https://boards.greenhouse.io/company\nhttps://jobs.ashbyhq.com/company\nhttps://company.com/careers"}/></label><div className="notice"><b>↗</b><p><strong>Use public pages.</strong> Login-only or bot-protected pages—including most LinkedIn search pages—are reported as blocked, never bypassed.</p></div></div>
   <div className="panel filters"><Heading n="02" title="Set your signal" copy="Comma-separate terms. Titles, descriptions, and links are checked."/><div className="grid"><label>Job titles<input value={titles} onChange={e=>setTitles(e.target.value)}/></label><label>Keywords<input value={keywords} onChange={e=>setKeywords(e.target.value)}/></label><label>Locations<input value={locations} onChange={e=>setLocations(e.target.value)} placeholder="Phoenix, Remote, Arizona"/></label><label>Exclude<input value={exclude} onChange={e=>setExclude(e.target.value)}/></label></div><div className="remote-row"><button className={remoteOnly?"switch on":"switch"} onClick={()=>setRemoteOnly(!remoteOnly)} aria-pressed={remoteOnly}><span/></button><div><strong>Remote roles only</strong><small>Include jobs explicitly marked remote</small></div></div><button className="scan" onClick={scan} disabled={state==="scanning"}>{state==="scanning"?"Scanning…":"Scan job pages"}<span>→</span></button><p className={`status ${state}`} aria-live="polite">{message}</p></div>
  </section>
  <section className="results" id="results"><div className="results-head"><div><div className="eyebrow">YOUR SHORTLIST</div><h2>{shown.length} opportunities</h2><p>Review, annotate, select, and export. Notes stay in this browser session.</p></div><button className="export" onClick={exportCsv} disabled={!shown.length}>↓ Export {selected.length?`${selected.length} selected`:"all"} as CSV</button></div><div className="tools"><input aria-label="Filter results" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter by title, company, or location…"/><button onClick={()=>setSelected(selected.length===shown.length?[]:shown.map(j=>j.id))}>{selected.length===shown.length&&shown.length?"Clear selection":"Select all"}</button></div><div className="job-list">
   {shown.map(job=><article className="job" key={job.id}><label className="check"><input type="checkbox" checked={selected.includes(job.id)} onChange={()=>setSelected(v=>v.includes(job.id)?v.filter(x=>x!==job.id):[...v,job.id])}/><span/></label><div className="job-body"><div className="job-top"><div><div className="company">{job.company} · {job.source}</div><h3><a href={job.url} target="_blank" rel="noreferrer">{job.title} <small>↗</small></a></h3></div><span className={`workplace ${job.workplace.toLowerCase().replace("-","")}`}>{job.workplace}</span></div><div className="facts"><span>⌖ {job.location}</span><span>◫ {job.pay}</span><span>◷ {job.posted}</span></div><div className="matches">{job.matched.map(m=><span key={m}>{m}</span>)}</div><input className="note" value={job.note||""} onChange={e=>setJobs(v=>v.map(j=>j.id===job.id?{...j,note:e.target.value}:j))} placeholder="Add a private note…"/></div></article>)}
   {!shown.length&&<div className="empty"><b>⌁</b><h3>No matches yet</h3><p>Try broader titles or remove a location filter.</p></div>}
  </div></section>
  <section className="how" id="how"><div><div className="eyebrow">BUILT FOR A FOCUSED SEARCH</div><h2>From noisy pages to a useful list.</h2></div><ol><li><b>1</b><strong>Add sources</strong><p>Paste public ATS boards or company career pages.</p></li><li><b>2</b><strong>Match signal</strong><p>Titles, descriptions, locations, and links are searched.</p></li><li><b>3</b><strong>Make it yours</strong><p>Add notes and export a tidy CSV for follow-up.</p></li></ol></section>
  <footer><strong>JOB COMPASS</strong><p>Public job discovery, organized.</p><small>*Dynamic or protected pages may return limited results.</small></footer>
 </main>
}
function Heading({n,title,copy}:{n:string;title:string;copy:string}){return <div className="heading"><span>{n}</span><div><h2>{title}</h2><p>{copy}</p></div></div>}
